[MOSIP-34578] Added check to verify roles .
Signed-off-by: abhishek8shankar <127825992+abhishek8shankar@users.noreply.github.com>

diff --git a/.github/workflows/chart-lint-publish.yml b/.github/workflows/chart-lint-publish.yml
--- a/.github/workflows/chart-lint-publish.yml
+++ b/.github/workflows/chart-lint-publish.yml
@@ -96,7 +96,25 @@ jobs:
           linting_chart_testing_config_yaml_url: "${{ inputs.LINTING_CHART_TESTING_CONFIG_YAML_URL }}"
           linting_health_check_schema_yaml_url: "${{ inputs.LINTING_HEALTH_CHECK_SCHEMA_YAML_URL }}"
           dependencies: "${{ inputs.DEPENDENCIES }}"
+          
+      - name: Check saroles in default role section
+        run: |
+          DEFAULT_ROLES=$(grep -A 1000 "roles:" keycloak.yaml | grep -B 1000 "client_scopes:" | grep -v "roles:" | grep -v "client_scopes:" | sed 's/^[ \t-]*//;s/[ \t-]*$//' | sort)
+          SAROLES=$(grep "saroles:" values.yaml -A 1000 | grep -v "saroles:" | grep -E -o '\- [A-Z_]*' | sed 's/^- //')
+          
+          MISSING_ROLES=""
+          for ROLE in $SAROLES; do
+            if ! grep -q "$ROLE" <<< "$DEFAULT_ROLES"; then
+              MISSING_ROLES+="$ROLE\n"
+            fi
+          done
 
+          if [ -n "$MISSING_ROLES" ]; then
+            echo -e "The following saroles are missing from the default role section:\n$MISSING_ROLES"
+            exit 1
+          else
+            echo "All saroles are included in the default role section."
+          fi
 
       # Commented below tasks as it cannot test MOSIP helm/charts deployment due to dependencies issues
       #- name: Create kind v1.21.1 cluster
